// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {document} from '../models';

export function Block(arg1:number,arg2:number):Promise<document.BlockDetail>;

export function BlockContent(arg1:number,arg2:number):Promise<string>;

export function CancelTask():Promise<void>;

export function ConfirmClose():Promise<void>;

export function DeleteBlock(arg1:number,arg2:number):Promise<document.Message>;

export function DeletePage(arg1:number):Promise<document.Message>;

export function DownloadAssets():Promise<document.ImportResult>;

export function ExportJSON():Promise<string>;

export function ExportMarkdown(arg1:document.MarkdownRequest):Promise<string>;

export function Import(arg1:string,arg2:boolean):Promise<document.ImportResult>;

export function MergeBlocks(arg1:number,arg2:string,arg3:string):Promise<document.Message>;

export function MoveBlock(arg1:number,arg2:number,arg3:string):Promise<document.Message>;

export function PageMarkdown(arg1:number):Promise<string>;

export function Pages(arg1:number):Promise<document.PagesResponse>;

export function ReorderBlocks(arg1:number,arg2:string):Promise<document.Message>;

export function Search(arg1:document.SearchRequest):Promise<document.SearchResponse>;

export function SelectImportFile():Promise<string>;

export function SetPageToolsVisible(arg1:boolean):Promise<void>;

export function SplitBlock(arg1:number,arg2:number,arg3:number):Promise<document.Message>;

export function Status():Promise<document.Status>;

export function UpdateBlock(arg1:document.UpdateBlockRequest):Promise<document.Message>;

export function View(arg1:number):Promise<document.PageView>;
