// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Block(arg1, arg2) {
  return window['go']['main']['App']['Block'](arg1, arg2);
}

export function BlockContent(arg1, arg2) {
  return window['go']['main']['App']['BlockContent'](arg1, arg2);
}

export function CancelTask() {
  return window['go']['main']['App']['CancelTask']();
}

export function ConfirmClose() {
  return window['go']['main']['App']['ConfirmClose']();
}

export function DeleteBlock(arg1, arg2) {
  return window['go']['main']['App']['DeleteBlock'](arg1, arg2);
}

export function DeletePage(arg1) {
  return window['go']['main']['App']['DeletePage'](arg1);
}

export function DownloadAssets() {
  return window['go']['main']['App']['DownloadAssets']();
}

export function ExportJSON() {
  return window['go']['main']['App']['ExportJSON']();
}

export function ExportMarkdown(arg1) {
  return window['go']['main']['App']['ExportMarkdown'](arg1);
}

export function Import(arg1, arg2) {
  return window['go']['main']['App']['Import'](arg1, arg2);
}

export function MergeBlocks(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeBlocks'](arg1, arg2, arg3);
}

export function MoveBlock(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveBlock'](arg1, arg2, arg3);
}

export function PageMarkdown(arg1) {
  return window['go']['main']['App']['PageMarkdown'](arg1);
}

export function Pages(arg1) {
  return window['go']['main']['App']['Pages'](arg1);
}

export function ReorderBlocks(arg1, arg2) {
  return window['go']['main']['App']['ReorderBlocks'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SelectImportFile() {
  return window['go']['main']['App']['SelectImportFile']();
}

export function SetPageToolsVisible(arg1) {
  return window['go']['main']['App']['SetPageToolsVisible'](arg1);
}

export function SplitBlock(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitBlock'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function UpdateBlock(arg1) {
  return window['go']['main']['App']['UpdateBlock'](arg1);
}

export function View(arg1) {
  return window['go']['main']['App']['View'](arg1);
}
